// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package org.atlas.gateway.components.wsn.messages;

public final class WSNMessage {
  private WSNMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AdvertismentOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.atlas.gateway.components.wsn.messages.Advertisment)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string address = 1;</code>
     */
    java.lang.String getAddress();
    /**
     * <code>optional string address = 1;</code>
     */
    com.google.protobuf.ByteString
        getAddressBytes();

    /**
     * <code>optional .org.atlas.gateway.components.wsn.messages.Advertisment.WirelessTechnology technology = 2;</code>
     */
    int getTechnologyValue();
    /**
     * <code>optional .org.atlas.gateway.components.wsn.messages.Advertisment.WirelessTechnology technology = 2;</code>
     */
    org.atlas.gateway.components.wsn.messages.WSNMessage.Advertisment.WirelessTechnology getTechnology();

    /**
     * <code>optional bytes data = 3;</code>
     */
    com.google.protobuf.ByteString getData();
  }
  /**
   * Protobuf type {@code org.atlas.gateway.components.wsn.messages.Advertisment}
   */
  public  static final class Advertisment extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.atlas.gateway.components.wsn.messages.Advertisment)
      AdvertismentOrBuilder {
    // Use Advertisment.newBuilder() to construct.
    private Advertisment(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Advertisment() {
      address_ = "";
      technology_ = 0;
      data_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Advertisment(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              address_ = s;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              technology_ = rawValue;
              break;
            }
            case 26: {

              data_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.atlas.gateway.components.wsn.messages.WSNMessage.internal_static_org_atlas_gateway_components_wsn_messages_Advertisment_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.atlas.gateway.components.wsn.messages.WSNMessage.internal_static_org_atlas_gateway_components_wsn_messages_Advertisment_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.atlas.gateway.components.wsn.messages.WSNMessage.Advertisment.class, org.atlas.gateway.components.wsn.messages.WSNMessage.Advertisment.Builder.class);
    }

    /**
     * Protobuf enum {@code org.atlas.gateway.components.wsn.messages.Advertisment.WirelessTechnology}
     */
    public enum WirelessTechnology
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>BLE = 0;</code>
       */
      BLE(0),
      /**
       * <code>ZIGBEE = 1;</code>
       */
      ZIGBEE(1),
      /**
       * <code>CC2420 = 2;</code>
       */
      CC2420(2),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>BLE = 0;</code>
       */
      public static final int BLE_VALUE = 0;
      /**
       * <code>ZIGBEE = 1;</code>
       */
      public static final int ZIGBEE_VALUE = 1;
      /**
       * <code>CC2420 = 2;</code>
       */
      public static final int CC2420_VALUE = 2;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static WirelessTechnology valueOf(int value) {
        return forNumber(value);
      }

      public static WirelessTechnology forNumber(int value) {
        switch (value) {
          case 0: return BLE;
          case 1: return ZIGBEE;
          case 2: return CC2420;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<WirelessTechnology>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          WirelessTechnology> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<WirelessTechnology>() {
              public WirelessTechnology findValueByNumber(int number) {
                return WirelessTechnology.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return org.atlas.gateway.components.wsn.messages.WSNMessage.Advertisment.getDescriptor().getEnumTypes().get(0);
      }

      private static final WirelessTechnology[] VALUES = values();

      public static WirelessTechnology valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private WirelessTechnology(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:org.atlas.gateway.components.wsn.messages.Advertisment.WirelessTechnology)
    }

    public static final int ADDRESS_FIELD_NUMBER = 1;
    private volatile java.lang.Object address_;
    /**
     * <code>optional string address = 1;</code>
     */
    public java.lang.String getAddress() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        address_ = s;
        return s;
      }
    }
    /**
     * <code>optional string address = 1;</code>
     */
    public com.google.protobuf.ByteString
        getAddressBytes() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        address_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TECHNOLOGY_FIELD_NUMBER = 2;
    private int technology_;
    /**
     * <code>optional .org.atlas.gateway.components.wsn.messages.Advertisment.WirelessTechnology technology = 2;</code>
     */
    public int getTechnologyValue() {
      return technology_;
    }
    /**
     * <code>optional .org.atlas.gateway.components.wsn.messages.Advertisment.WirelessTechnology technology = 2;</code>
     */
    public org.atlas.gateway.components.wsn.messages.WSNMessage.Advertisment.WirelessTechnology getTechnology() {
      org.atlas.gateway.components.wsn.messages.WSNMessage.Advertisment.WirelessTechnology result = org.atlas.gateway.components.wsn.messages.WSNMessage.Advertisment.WirelessTechnology.valueOf(technology_);
      return result == null ? org.atlas.gateway.components.wsn.messages.WSNMessage.Advertisment.WirelessTechnology.UNRECOGNIZED : result;
    }

    public static final int DATA_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>optional bytes data = 3;</code>
     */
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getAddressBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, address_);
      }
      if (technology_ != org.atlas.gateway.components.wsn.messages.WSNMessage.Advertisment.WirelessTechnology.BLE.getNumber()) {
        output.writeEnum(2, technology_);
      }
      if (!data_.isEmpty()) {
        output.writeBytes(3, data_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getAddressBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, address_);
      }
      if (technology_ != org.atlas.gateway.components.wsn.messages.WSNMessage.Advertisment.WirelessTechnology.BLE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, technology_);
      }
      if (!data_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, data_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.atlas.gateway.components.wsn.messages.WSNMessage.Advertisment)) {
        return super.equals(obj);
      }
      org.atlas.gateway.components.wsn.messages.WSNMessage.Advertisment other = (org.atlas.gateway.components.wsn.messages.WSNMessage.Advertisment) obj;

      boolean result = true;
      result = result && getAddress()
          .equals(other.getAddress());
      result = result && technology_ == other.technology_;
      result = result && getData()
          .equals(other.getData());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getAddress().hashCode();
      hash = (37 * hash) + TECHNOLOGY_FIELD_NUMBER;
      hash = (53 * hash) + technology_;
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.atlas.gateway.components.wsn.messages.WSNMessage.Advertisment parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.atlas.gateway.components.wsn.messages.WSNMessage.Advertisment parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.atlas.gateway.components.wsn.messages.WSNMessage.Advertisment parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.atlas.gateway.components.wsn.messages.WSNMessage.Advertisment parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.atlas.gateway.components.wsn.messages.WSNMessage.Advertisment parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.atlas.gateway.components.wsn.messages.WSNMessage.Advertisment parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.atlas.gateway.components.wsn.messages.WSNMessage.Advertisment parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.atlas.gateway.components.wsn.messages.WSNMessage.Advertisment parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.atlas.gateway.components.wsn.messages.WSNMessage.Advertisment parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.atlas.gateway.components.wsn.messages.WSNMessage.Advertisment parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.atlas.gateway.components.wsn.messages.WSNMessage.Advertisment prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.atlas.gateway.components.wsn.messages.Advertisment}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.atlas.gateway.components.wsn.messages.Advertisment)
        org.atlas.gateway.components.wsn.messages.WSNMessage.AdvertismentOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.atlas.gateway.components.wsn.messages.WSNMessage.internal_static_org_atlas_gateway_components_wsn_messages_Advertisment_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.atlas.gateway.components.wsn.messages.WSNMessage.internal_static_org_atlas_gateway_components_wsn_messages_Advertisment_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.atlas.gateway.components.wsn.messages.WSNMessage.Advertisment.class, org.atlas.gateway.components.wsn.messages.WSNMessage.Advertisment.Builder.class);
      }

      // Construct using org.atlas.gateway.components.wsn.messages.WSNMessage.Advertisment.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        address_ = "";

        technology_ = 0;

        data_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.atlas.gateway.components.wsn.messages.WSNMessage.internal_static_org_atlas_gateway_components_wsn_messages_Advertisment_descriptor;
      }

      public org.atlas.gateway.components.wsn.messages.WSNMessage.Advertisment getDefaultInstanceForType() {
        return org.atlas.gateway.components.wsn.messages.WSNMessage.Advertisment.getDefaultInstance();
      }

      public org.atlas.gateway.components.wsn.messages.WSNMessage.Advertisment build() {
        org.atlas.gateway.components.wsn.messages.WSNMessage.Advertisment result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.atlas.gateway.components.wsn.messages.WSNMessage.Advertisment buildPartial() {
        org.atlas.gateway.components.wsn.messages.WSNMessage.Advertisment result = new org.atlas.gateway.components.wsn.messages.WSNMessage.Advertisment(this);
        result.address_ = address_;
        result.technology_ = technology_;
        result.data_ = data_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.atlas.gateway.components.wsn.messages.WSNMessage.Advertisment) {
          return mergeFrom((org.atlas.gateway.components.wsn.messages.WSNMessage.Advertisment)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.atlas.gateway.components.wsn.messages.WSNMessage.Advertisment other) {
        if (other == org.atlas.gateway.components.wsn.messages.WSNMessage.Advertisment.getDefaultInstance()) return this;
        if (!other.getAddress().isEmpty()) {
          address_ = other.address_;
          onChanged();
        }
        if (other.technology_ != 0) {
          setTechnologyValue(other.getTechnologyValue());
        }
        if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
          setData(other.getData());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.atlas.gateway.components.wsn.messages.WSNMessage.Advertisment parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.atlas.gateway.components.wsn.messages.WSNMessage.Advertisment) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object address_ = "";
      /**
       * <code>optional string address = 1;</code>
       */
      public java.lang.String getAddress() {
        java.lang.Object ref = address_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          address_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string address = 1;</code>
       */
      public com.google.protobuf.ByteString
          getAddressBytes() {
        java.lang.Object ref = address_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          address_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string address = 1;</code>
       */
      public Builder setAddress(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        address_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string address = 1;</code>
       */
      public Builder clearAddress() {
        
        address_ = getDefaultInstance().getAddress();
        onChanged();
        return this;
      }
      /**
       * <code>optional string address = 1;</code>
       */
      public Builder setAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        address_ = value;
        onChanged();
        return this;
      }

      private int technology_ = 0;
      /**
       * <code>optional .org.atlas.gateway.components.wsn.messages.Advertisment.WirelessTechnology technology = 2;</code>
       */
      public int getTechnologyValue() {
        return technology_;
      }
      /**
       * <code>optional .org.atlas.gateway.components.wsn.messages.Advertisment.WirelessTechnology technology = 2;</code>
       */
      public Builder setTechnologyValue(int value) {
        technology_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .org.atlas.gateway.components.wsn.messages.Advertisment.WirelessTechnology technology = 2;</code>
       */
      public org.atlas.gateway.components.wsn.messages.WSNMessage.Advertisment.WirelessTechnology getTechnology() {
        org.atlas.gateway.components.wsn.messages.WSNMessage.Advertisment.WirelessTechnology result = org.atlas.gateway.components.wsn.messages.WSNMessage.Advertisment.WirelessTechnology.valueOf(technology_);
        return result == null ? org.atlas.gateway.components.wsn.messages.WSNMessage.Advertisment.WirelessTechnology.UNRECOGNIZED : result;
      }
      /**
       * <code>optional .org.atlas.gateway.components.wsn.messages.Advertisment.WirelessTechnology technology = 2;</code>
       */
      public Builder setTechnology(org.atlas.gateway.components.wsn.messages.WSNMessage.Advertisment.WirelessTechnology value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        technology_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .org.atlas.gateway.components.wsn.messages.Advertisment.WirelessTechnology technology = 2;</code>
       */
      public Builder clearTechnology() {
        
        technology_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes data = 3;</code>
       */
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>optional bytes data = 3;</code>
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes data = 3;</code>
       */
      public Builder clearData() {
        
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:org.atlas.gateway.components.wsn.messages.Advertisment)
    }

    // @@protoc_insertion_point(class_scope:org.atlas.gateway.components.wsn.messages.Advertisment)
    private static final org.atlas.gateway.components.wsn.messages.WSNMessage.Advertisment DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.atlas.gateway.components.wsn.messages.WSNMessage.Advertisment();
    }

    public static org.atlas.gateway.components.wsn.messages.WSNMessage.Advertisment getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Advertisment>
        PARSER = new com.google.protobuf.AbstractParser<Advertisment>() {
      public Advertisment parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Advertisment(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Advertisment> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Advertisment> getParserForType() {
      return PARSER;
    }

    public org.atlas.gateway.components.wsn.messages.WSNMessage.Advertisment getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_atlas_gateway_components_wsn_messages_Advertisment_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_atlas_gateway_components_wsn_messages_Advertisment_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rmessage.proto\022)org.atlas.gateway.compo" +
      "nents.wsn.messages\"\304\001\n\014Advertisment\022\017\n\007a" +
      "ddress\030\001 \001(\t\022^\n\ntechnology\030\002 \001(\0162J.org.a" +
      "tlas.gateway.components.wsn.messages.Adv" +
      "ertisment.WirelessTechnology\022\014\n\004data\030\003 \001" +
      "(\014\"5\n\022WirelessTechnology\022\007\n\003BLE\020\000\022\n\n\006ZIG" +
      "BEE\020\001\022\n\n\006CC2420\020\002B7\n)org.atlas.gateway.c" +
      "omponents.wsn.messagesB\nWSNMessageb\006prot" +
      "o3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_org_atlas_gateway_components_wsn_messages_Advertisment_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_atlas_gateway_components_wsn_messages_Advertisment_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_atlas_gateway_components_wsn_messages_Advertisment_descriptor,
        new java.lang.String[] { "Address", "Technology", "Data", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
